version: '3.7'
services:
        mysql:
                image: mysql:8.0.16
                ports:
                        - 127.0.0.1:3306:3306
                # volumes:
                #         - ./tmp/mysql:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=123456
                        - MYSQL_USER=john
                        - MYSQL_PASSWORD=123456
                        - MYSQL_DATABASE=test
